authors = ["pealz1"]
description = "Typed, buffer-packed and secure networking for Roblox, compiled from a schema"
includes = [
    "README.md",
    "pesde.toml",
    "release/cheeto_pesde.luau",
]
license = "MIT"
name = "pealz1/cheeto"
repository = "https://github.com/pealz1/cheeto"
version = "1.1.0"

[indices]
default = "https://github.com/pesde-pkg/index"

[target]
bin = "release/cheeto_pesde.luau"
environment = "lune"
